version: '3'

volumes:
  db:
    driver: local
    driver_opts:
      device: /home/dtanigaw/data/database
      type: volume
      o: bind
  wordpress-volume:
    driver: local
    driver_opts:
      device: /home/dtanigaw/data/wordpress
      type: volume
      o: bind

networks:
  inception:

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: img_nginx
    volumes:
      - wordpress-volume:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    ports:
      - 443:443
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress
    expose:
      - 9000
    volumes:
      - wordpress-volume:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped